# Generated by Django 4.1.7 on 2023-06-03 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='first',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Участник 1+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='second',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Участник 2+', to=settings.AUTH_USER_MODEL),
        ),
    ]
