# Generated by Django 4.1.7 on 2023-03-20 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='Почта пользователя')),
                ('password', models.CharField(default='', max_length=1024)),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='аватар пользователя')),
                ('name', models.CharField(default='', max_length=256, verbose_name='Имя исполнителя')),
                ('surname', models.CharField(default='', max_length=256, verbose_name='Фамилия исполнителя')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст исполнителя')),
                ('info', models.CharField(default='', max_length=1024, verbose_name='Общая информация о исполнителе')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Кол-во отзывов')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image', verbose_name='фотография услуги')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок услуги')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание услуги')),
                ('stack', models.CharField(max_length=512, verbose_name='Стек технологии')),
                ('price', models.IntegerField(default=0, verbose_name='Цена услуги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор карточки')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5096, verbose_name='Текст отзыва')),
                ('estimation', models.IntegerField(default=0, verbose_name='Оценка')),
                ('user_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
                ('user_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL, verbose_name='Адресат отзыва')),
            ],
        ),
    ]
