# Generated by Django 4.1.7 on 2023-05-17 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_executor', to=settings.AUTH_USER_MODEL),
        ),
    ]
