# Generated by Django 4.1.7 on 2023-05-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='files',
        ),
    ]
