# Generated by Django 4.1.7 on 2023-04-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0002_remove_order_file_file_order_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='order',
        ),
    ]
