# Generated by Django 4.1.7 on 2023-06-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0002_order_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar', verbose_name='аватар пользователя'),
        ),
    ]
