# Generated by Django 4.1.7 on 2023-05-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0002_remove_order_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='executors.order'),
        ),
    ]
