# Generated by Django 4.1.7 on 2023-05-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0003_alter_file_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, upload_to='files/order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.CharField(default='Не указано', max_length=64, null=True, verbose_name='Срок выполнения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(default=None, max_length=1024, verbose_name='Описание заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='kind',
            field=models.CharField(blank=True, default=None, max_length=256, verbose_name='Тип заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stack',
            field=models.CharField(blank=True, max_length=512, verbose_name='Стек технологии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Создан', max_length=32, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Заголовок заказа'),
        ),
    ]
