# Generated by Django 4.1.7 on 2023-05-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0004_order_file_alter_order_deadline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
